# docker-compose.yml

version: '3.8'

services:
  app:
    build: .
    container_name: retail_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8501:8501"  # Streamlit
      - "8888:8888"  # Jupyter Notebook
    depends_on:
      - db
    command: bash

  db:
    image: postgres:14
    container_name: retail_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adventureworks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
