retail_intelligence:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: retail_intelligence
      schema: marts
      threads: 4

